spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driner-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
    cache: false
